name: Scalingo
on:
  push:
    branches:
      - staging
jobs:
  scalingo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH_PRIVATE_KEY }}
      - name: Update known hosts
        run: ssh-keyscan -H ssh.osc-fr1.scalingo.com >> ~/.ssh/known_hosts
      - name: Push to Scalingo
        run: |
          git push ${{ secrets.SCALINGO_STAGING_REMOTE }} staging:master